trigger:
  - main  # Adjust to your branch

pool:
  vmImage: 'ubuntu-latest'  # Runs on an Ubuntu agent

variables:
 # - template: variables/variables.yaml
  - group: "ACA_VARIABLES" # specific to AzureDevOps 

steps: 
  - task: AzureCLI@2
    displayName: 'Azure Login'
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Logging into Azure..."
        az login --service-principal --username "$(APP_ID)" --password "$(CLIENT_SECRET)" --tenant "$(TENANT_ID)"

  - script: | # Docker Login
      echo "Logging into Azure Container Registry..."
      docker login "$(ACR_NAME)" -u "$(ACR_USERNAME)" -p "$(ACR_PASSWORD)"
    displayName: 'Docker Login to Azure Container Registry'

  - task: Docker@2
  displayName: Build and push Docker image
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'  # Path to your Dockerfile
    repository: "$(TARGET_IMAGE)"  # e.g., mycontainerregistry.azurecr.io/my-app
    tags: latest
    displayName: 'Build, Tag, and Push Falcon Sensor'

  - task: AzureCLI@2
    displayName: 'Deploy to Azure Container Apps'
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Deploying patched container to Azure Container Apps..."
        az containerapp update \
          --name "$(CONTAINER_APP_NAME)" \
          --resource-group "$(RESOURCE_GROUP)" \
          --image "$(TARGET_IMAGE)"
